model:
  depth: 6
  width: 512
  use_lln: True
  num_lc_iter: 10
  act_name: "MinMax"
  stem_kernel_size: 5
  backbone_type: "bro"
  backbone_centering: True
  backbone_weight_rank_ratio: 0.125

  neck_conv_type: "bro"
  neck_linear_type: "bro"

  dense_width: 2048
  dense_type: "bro"
  dense_weight_rank_ratio: 0.125
  linear_num: 4

training:
  batch_size: 256
  epochs: 800
  warmup_epochs: 20
  lr: 1.0e-3
  weight_decay: 4.0e-5
  grad_clip: True
  grad_clip_val: 3
  nadam: True
  lion: False
  sgd: False
  momentum: 0.0
  lookahead: True

dataset:
  name: "tiny_imagenet"
  num_classes: 200
  input_size: 64
  ddpm: False
  ddpm_ratio: 0

loss:
  eps: 0.1411764705882353
  min_eps_ratio: 0.1
  max_eps_ratio: 3.0
  loss_type: "logit_annealing_loss"
  gamma: 5.0
  temperature: 0.75
  offset: 2.0
